[package]
name = "tri_ton"
authors = ["u/nondescript_potato"]
description = "A Macro for Handling Exceptions"
readme = "README.md"
repository = "https://github.com/EMcConnell20/tri_ton.git"
keywords = ["macro", "utility", "enum"]
version = "0.0.1"
edition = "2021"
